namespace client
{
    using System;

    public enum FeedType
    {
        _POST_PRODUCT_DATA_,
        _POST_PRODUCT_RELATIONSHIP_DATA_,
        _POST_ITEM_DATA_,
        _POST_PRODUCT_OVERRIDES_DATA_,
        _POST_PRODUCT_IMAGE_DATA_,
        _POST_PRODUCT_PRICING_DATA_,
        _POST_INVENTORY_AVAILABILITY_DATA_,
        _POST_ORDER_ACKNOWLEDGEMENT_DATA_,
        _POST_ORDER_FULFILLMENT_DATA_,
        _POST_FULFILLMENT_ORDER_REQUEST_DATA_,
        _POST_FULFILLMENT_ORDER_CANCELLATION_REQUEST_DATA_,
        _POST_PAYMENT_ADJUSTMENT_DATA_,
        _POST_INVOICE_CONFIRMATION_DATA_
    }
}

